# These are supported funding model platforms

github: [garage-ai]
patreon: garageai
open_collective: garage-ai
ko_fi: garageai
tidelift: npm/garage-ai
community_bridge: garage-ai
liberapay: garage-ai
issuehunt: garage-ai
otechie: garage-ai
custom: ['https://garage.ai/donate', 'https://www.paypal.me/garageai']
